[server]
redirect_url = "http://localhost:4001/"
base_url = "http://localhost:4001/api/v1"
secure_sessions = false
bot.enabled = true

[mmr]
model = "openskill"
command = "uv run main.py"
tau = 0.08333333333
defaults.rating = 25
defaults.deviation = 8.333333333333

[http]
port = 4000
